### ISSUE TITLE
Slack integration fails with "Bridge returned HTTP 500 Internal Server Error: Guest access not allowed"

### ISSUE THREAD

**Issue by madduck** [matrix-org/matrix-appservice-slack#102]
I'm trying to add a Slack bridge (from the Modular offering on `riot.im`) to a Matrix room. The room is set to public incl. guests.. When I punch in the incoming web hook from Slack and hit "Save integration", the following message is displayed:

> Bridge returned HTTP 500 Internal Server Error: Guest access not allowed

This is utterly confusing. Where is guest access not allowed?

On the Slack side of things, the bridge is set up correctly. I can run a command such as

```
curl -X POST --data-urlencode 'payload={"channel": "#general", "username": "[Matrix]", "text": "Please ignore this test message", "icon_emoji": ":ghost:"}' https://hooks.slack.com/services/…/…/…
```

and that yields a message in the channel, so guest access works just fine.

And the Matrix room is configured to allow guest access, too.

There's something going wrong here somewhere, and the error messages are not
at all helpful.

**Comment by Half-Shot** [comment]
"Bridge returned HTTP 500 Internal Server Error: Guest access not allowed" happens when we try to check state on the room but are not joined yet, giving the confusing impression that you need guest access enabled. I've written some code in a PR already that forces it to join first, so this should be fixed.

**Comment by Half-Shot** [comment]
Err, disinvite and invite the bot?

**Comment by madduck** [comment]
Seems like the thing to do, @Half-Shot, but I cannot seem to disinvite: https://github.com/vector-im/riot-web/issues/2989

**Comment by Half-Shot** [comment]
Oh good.

**Comment by Half-Shot** [comment]
Should have fixed this in develop

**Comment by pooja** [comment]
Hi @Half-Shot I'm seeing this message currently when trying to bridge a matrix room to my slack workspace. Any thoughts?

**Comment by Half-Shot** [comment]
@pooja did you invite the bot to the room?

**Comment by pooja** [comment]
Hey @Half-Shot, I think this issue was related to the new infra deployment. It works now, in any case! :)

**Comment by sitiom** [comment]
It fails again with the HTTP 500 error (https://github.com/matrix-org/matrix-appservice-slack/issues/617)
