### ISSUE TITLE
Handle Substitutions Better!

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-appservice-slack#110]
Currently we have the situation where a slack event goes through the following pipe:

`SlackEventHandler.handleMessageEvent` -> 
`SlackEventHandler.replaceChannelldsWithNames` -> 
`SlackEventHandler.replaceUserIdsWithNames` -> `BridgedRoom.onSlackMessage` -> {`subsitutions.slacktoMatrix`} -> `SlackGhost.sendText`

At nearly every stage of this pipe some replacement on the original slack message text is done. Only at the *very* end `SlackGhost.sendText` does `Slackdown` get called to generate the `formatted_body` this means that that as it is currently set up *either* we have to send valid slackdown as the body or we can't do interesting things like pills-ifying the slack side user mentions like we are currently doing in `replaceUserIdsWithNames`.

This is especially egregious for the pills mentions we are injecting, as we are injecting then as slackdown style links i.e. `<https://matrix.to/...|Cadair>` which look *really* bad in the plain text body (and in fact are a horrible way to mention someone.

What I suggest we do is refactor all the subsitutions so that we have one call which when given a slack plain text generates a plain body and a formatted body pair, meaning we can handle different subs for each.

**Comment by Half-Shot** [comment]
Agreed! I think we should probably end up with a class that transform between plaintext and markdown from a slackdown source ideally.

**Comment by Half-Shot** [comment]
I think this issue has probably little value now the bridge is in TS. Specific grievances with the subs code should be in self contained smaller issues.
