### ISSUE TITLE
Username mentions are broken on matrix.org

### ISSUE THREAD

**Issue by z3ntu** [matrix-org/matrix-appservice-slack#113]
![image](https://user-images.githubusercontent.com/3768500/47603210-2ff51b80-d9e9-11e8-8040-c71af4dd880d.png)

(It wasn't broken on October 5th and before.)

**Comment by Half-Shot** [comment]
Thanks for filing, can you either tell me or PM me (@Half-shot:half-shot.uk) the slack channel/workspace name and the roomid. This sounds like something we can hotfix

**Comment by Cadair** [comment]
This seems to be limited to webhooks in my experience.

**Comment by Half-Shot** [comment]
We fixed this kind of stuff in #280
