### ISSUE TITLE
Slack Event Bot integration not possible without running own server 

### ISSUE THREAD

**Issue by deerdear** [matrix-org/matrix-appservice-slack#114]
Trying to integrate a private slack channel with a Matrix room using the Events Subscriptions but since I'm using the Matrix homeserver I don't know what the request URL should be. 

Maybe this isn't a real issue, just me not knowing what is meant...

**Comment by antonok-edm** [comment]
Looks like this functionality is available on Riot now.

**Comment by Half-Shot** [comment]
It is indeed. Closing.
