### ISSUE TITLE
Add ability to Pills known rooms

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-appservice-slack#115]
Currently a room mention on slack is bridged as `#roomname` if the appservice is bridging the other room, we could make this into a pill, and also in reverse, convert a bridged room pill to a slack room link.

This is particularly relevant where you might have many (or all) rooms in one slack team bridged into matrix. This would probably require keeping a cache of all room aliases for all bridged rooms. We would probably only want to allow pillsifyng of rooms within one slack team rather than globally.

**Comment by Half-Shot** [comment]
We did this?
