### ISSUE TITLE
Reduce permissions of Riot Bridge Slack app

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/matrix-appservice-slack#117]
Many Slack Workspaces admins refuse adding Riot Bridge Slack app because it want too many permissions, can we try to reduce them?
The most asked permission is "View email addresses of people on this workspace", so Riot Bridge Slack app will give access to private info of all workspace users - can we remove it, or make optional?

**Comment by Half-Shot** [comment]
Sure, it was probably added in over my confusion of the slack permission system. I'll need to identify which one(s) are the problematic ones and check that it still works.

**Comment by Half-Shot** [comment]
Looks like `users:read`. I believe we use this to get the profiles of users in the workspace so it might not be possible to remove it :/

**Comment by Half-Shot** [comment]
Nevermind, users:read.email is needed to access a users email address.

**Comment by MurzNN** [comment]
For what bridge needs user emails for bridging? Can you make it optional?

**Comment by Half-Shot** [comment]
We don't require it:

https://github.com/matrix-org/matrix-appservice-slack/blob/e421200dc545faf6acf9e6facdaeae8cc12d0bcb/lib/OAuth2.js#L9

![image](https://user-images.githubusercontent.com/2072976/52916720-01be8300-32db-11e9-9978-05288e9f8b35.png)

**Comment by MurzNN** [comment]
Seems Slack fixes the description of this permission, now it is:

> Access information about your workspace
> Riot Bridge will be able to access information about Drupal, including name, email domain, and icon.View email addresses of people on this workspace

So it tell only the domain of email.
