### ISSUE TITLE
Slack->Matrix doesn't get bridged w/ Events API

### ISSUE THREAD

**Issue by barudaret** [matrix-org/matrix-appservice-slack#124]
I'm using the bridge hosted on matrix.org, I bridged a room with the events api.  Messages sent in matrix show up in slack, but nothing from slack shows up in matrix. 

![screenshot](https://user-images.githubusercontent.com/32847759/54876268-2621e980-4dca-11e9-85a2-e669fc63ac58.jpg)

**Comment by Half-Shot** [comment]
That's odd, I've seen the reverse before but not this. Is your room private/did the ghost join the room?

**Comment by barudaret** [comment]
Good question. The room is private on the matrix side. I didn't figure that's be a problem, because earlier I tried bridging the same matrix and slack rooms together with the old webhooks api.  With webhooks, S->M works just fine, ghost users join the room and everything, doesn't matter that it's private (and in that case it's M->S that's the problem because for some reason the bot wouldn't assume the name/avatar of the matrix user).  Next time I get to my laptop, I'll try it with the room public and see if that gets us somewhere.

**Comment by barudaret** [comment]
Okay, making the room public and reestablishing the bridge doesn't fix it.  S->M still doesn't work.  It's just a test channel, I don't mind if you pop in and tinker.  Please feel free, it's #LodvosprMnbFUQIczh:ostavrosnika.com and on the slack side, here's the invite: https://join.slack.com/t/anastasiosworkspace/shared_invite/enQtNTY5NTMwNDQ1NDI1LTY0OTY4OTU2MzFiNTQyZTM2MzMwMWJmY2MwOGZjZDI0NzUxNzFlOGUwNWRkMjE0ODAyYTk0YTg3NDhiY2RmMzU

**Comment by barudaret** [comment]
heads up: I think the invite expires tomorrow

**Comment by barudaret** [comment]
Well I found out what's the problem.  Apparently, even if you add a bot to a workspace, it can't join a channel in that workspace without being explicitly invited.  So I invited @riot_bridge to the slack channel and now S->M works.  It took me long enough to figure this out.  Is this in some setup instruction document somewhere?  I didn't see it anywhere.

**Comment by Half-Shot** [comment]
Okay, I think this issue has been reported before. We need to fix the docs.
