### ISSUE TITLE
Should we bridge !here in slack to @room in matrix?

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-appservice-slack#134]
Discuss

**Comment by turt2live** [comment]
yes

**Comment by olmari** [comment]
Sounds logical as default.. if slack and/or matrix has settings not to allow that, it would also needed to take into consideration.

**Comment by auscompgeek** [comment]
@olmari afaik if `@here` is disabled, users will never be able to send `<!here>` (which is what actually gets sent in slack mrkdwn).

`@here`/`@channel` can be restricted to admins only in Slack iirc. I think it'd be reasonable to unconditionally bridge `!channel` to `@room`. Same with `!here` depending on what's decided.

I suspect some people would prefer Slack's behaviour of only notifying active users on `@here`. Perhaps it'd be worth proposing an equivalent in Matrix.

**Comment by Cadair** [comment]
Implemented.
