### ISSUE TITLE
Implement removal of reactions

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-appservice-slack#154]
Currently we add reactions in both directions but can't remove them across the bridge.

For matrix -> slack reaction removal, the issue is when we *add* the reaction to slack, the `reactions.add` slack API method doesn't return the ts of the reaction event. You would have to listen for the event to come in on the event stream.

For slack -> matrix removal, the issue is that the slack event `reaction_removed` also dosen't give you the ts of the reaction event, it gives you the ts of the parent event as well as the sender of the reaction and the key of the reaction. This therefore means we would have to use the not-finished-yet aggregations API to query synapse for the event ID that matched those parameters.

**Comment by Half-Shot** [comment]
See also #131
