### ISSUE TITLE
Bridge private slack channels using the events API

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#159]
This is probably possible, but we've not really looked into it yet.

**Comment by Cadair** [comment]
Can confirm it is possible, you need to subscribe to a different event stream to make it work but it does.

**Comment by ADmad** [comment]
Currently if I use "Manage integrations" on riot.im webapp and select "event bridging" for Slack it provides a list of channels which doesn't include private channels.

**Comment by Cadair** [comment]
It's not enabled on the matrix.org bridge but you can configure it to work if you host it yourself.

**Comment by ADmad** [comment]
Okay, thanks. I'll submit an issue on Riot's repo then :slightly_smiling_face:

**Comment by Half-Shot** [comment]
This was previously broken because we were calling the wrong slack method (`channels.list` is wrong, and now we use `conversations.list`).

**Comment by Evidlo** [comment]
Has this change been deployed on matrix.org?

**Comment by kevincox** [comment]
Should this be reopened? This was originally marked as solved in Sep 2019 but it didn't seem to do the trick. https://github.com/matrix-org/matrix-appservice-slack/pull/403 was merged in May but I still can't bridge a private room (which myself and riot_bridge are a member of). Are we sure that this works correctly?

**Comment by Half-Shot** [comment]
It works, but it's only for self hosted / modular.im users of the slack bridge. The free matrix.org bridge doesn't support private channel bridging.

**Comment by kevincox** [comment]
Ah, I see.  Is there a place where we can request changes to the matrix.org configuration? Or is there a reason that this is unsuitable for public use?

**Comment by kevincox** [comment]
Actually I just tested this on Mozilla's matrix which I believe is a Modular instance and couldn't add a private channel either.

**Comment by Half-Shot** [comment]
>Actually I just tested this on Mozilla's matrix which I believe is a Modular instance and couldn't add a private channel either.

I should have mentioned that this is only for Modular hosts who have paid for their own Slack bridge, not hosts which use the free  matrix.org bridge.

**Comment by ara4n** [comment]
to be clear: the free slack bridge instance run on matrix.org doesn't have private slack channel bridging turned on. in order to bridge private stuff, you need a dedicated slack bridge (e.g. the paid hosting from modular.im, or running your own).

**Comment by JesseNaranjo** [comment]
@ara4n How come it's off on matrix.org? Is there some sort of limitation or increased resource usage to support private channels?

**Comment by tobiasBora** [comment]
Hey, is there any news on this? Is it because of the business model of matrix.org, or is it disabled for other reasons? Is there another place where we could report this?
