### ISSUE TITLE
SlackEventHandler failed

### ISSUE THREAD

**Issue by kingoftheconnors** [matrix-org/matrix-appservice-slack#162]
I have set up the Matrix Slack Bridge. The inbound url has been verified by the slack api, and I've been able to follow the directions by the appservice README, so a lot more progress has been made.

Right now there's a problem in linking channels, since the bridge doesn't seem to recognize when channels are linked and just says
```Oops - SlackEventHandler failed: UnknownChannel { channel: 'CJVQ3ATT8' }```
to all messages, regardless of which channel it's in.

I invited the Slack Bot to my room, but it seems to be offline, and I got no response or message of any kind when I attempted to use the linking command.

**Comment by Half-Shot** [comment]
Hmm, but it did say that it linked successfully. What is inside your `room-store.db` ? (It's just a JSON file)

**Comment by Cadair** [comment]
Have you configured the admin room to issue the link commands?

**Comment by kingoftheconnors** [comment]
Oh.

There is no room-store.db

And yes, I set the Matrix admin room's ID in the config file.

**Comment by kingoftheconnors** [comment]
No wait! I broke the configuration a while ago while looking for a solution. One second.

**Comment by kingoftheconnors** [comment]
OK. The data folder (which I set using dbdir) is empty. No room-store.db, no user-store.db

The full message on the terminal was:
```
Received slack event: {"token":"YpM6K2F5cwdjNJDxq6eJQS0J","team_id":"TJG60DCAX","api_app_id":"AKLKS636K","event":{"client_msg_id":"2fec6a84-945d-4f7e-90b1-156660a53f1b","type":"message","text":"d","user":"UJG6TFWM8","ts":"1563198942.000400","team":"TJG60DCAX","channel":"CJTK6K8NL","event_ts":"1563198942.000400","channel_type":"channel"},"type":"event_callback","event_id":"EvL39SAWD9","event_time":1563198942,"authed_users":["UJG6TFWM8"]}
Oops - SlackEventHandler failed: UnknownChannel { channel: 'CJTK6K8NL' }
```

**Comment by Cadair** [comment]
It hasn't linked the rooms. If it is ignoring the link commands in the admin room make sure synapse hasn't rate limited the AS into the ground.

**Comment by kingoftheconnors** [comment]
How do I test that? And is the Slack bot supposed to be offline? I can't find any way to get the bot online.

**Comment by kingoftheconnors** [comment]
Solved! Thank you for your help!

The problem was that both the URL forwarded to by the registration file's url (which was supposed to point to the **matrix** port) and the inbound uri (which was supposed to be the gate to the **slack** port) were set to point to the slack port and only the slack port.

After the URL variable in the registration file was set to connect to the Matrix port, the bridge became able to handle matrix-side events, including inviting the bot, linking channels and sending messages!
