### ISSUE TITLE
Feature request: Support edits properly on matrix

### ISSUE THREAD

**Issue by olmari** [matrix-org/matrix-appservice-slack#163]
Now that Matrix has proper support for message editing, make use of the mechanism in both directions (if possible).

**Comment by Cadair** [comment]
This is already implemented in 0.3rc

**Comment by olmari** [comment]
Okay cool. I did try to search but didn't find. Very nice then indeed!

**Comment by Cadair** [comment]
I believe the latest rc is deployed on the matrix.org bridge if that's the instance you are using.
