### ISSUE TITLE
A redaction on matrix seems to trigger more redactions on matrix

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#173]
Presumably this is because us deleting things on slack causes it to trigger us, in a loop.

**Comment by Cadair** [comment]
I don't know why the existing reflection filtering isn't catching `message_deleted` events, but it should.

**Comment by auscompgeek** [comment]
If I understand what this is about, this has interesting consequences when a message is redacted and a new message is quickly sent afterwards (such as when matrix-appservice-discord processes an edit on Discord), where the new message also gets redacted. [Here is a screencast](https://vovo.id.au/tmp/bridging-redactions.webm) demonstrating what I mean.

**Comment by Half-Shot** [comment]
@auscompgeek That looks like a discord bug to me -- can you tell me who redacted the event on matrix at the end?

**Comment by auscompgeek** [comment]
It looks like the latest redactions on both messages came from `@slackbot:matrix.org`.

**Comment by auscompgeek** [comment]
Hm, after updating my homeserver and turning on show hidden events in Riot, it looks like there is indeed a bug in matrix-appservice-discord. I'll file a bug over there.
