### ISSUE TITLE
Substrings of pills should not turn into Slack mentions

### ISSUE THREAD

**Issue by auscompgeek** [matrix-org/matrix-appservice-slack#183]

**Comment by Half-Shot** [comment]
What do you mean by "substrings" of pills. Are you talking about user_ids, displaynames, or literally a Matrix HTML pill sawed in half?

**Comment by auscompgeek** [comment]
My display name on Slack is a substring of a display name of one of my alter-egos - messages with a pill for said alter-ego end up on Slack with a Slack mention.

**Comment by Cadair** [comment]
Matrix pills to slack mentions should only match on slack user id. The plain text nick translations I could see doing this though, maybe there is a bug where both are happening?!

**Comment by Cadair** [comment]
Actually, now I think about it, this is the plain text mention machinery. I don't think it ignores pills.
