### ISSUE TITLE
Consider how "teams" will work

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-slack#19]
For a general-purpose bridge (e.g. the one matrix.org themselves run) it is insufficient to create Matrix-side ghosts named simply after the local username within one slack team - if there are many teams there will be many "Bob"s. In general the Matrix-side usernames have to include the Slack team name as well.

However, for most small-scale deployments by individuals, they will probably not want this. So consider adding a "single-team mode" to the bridge, which restricts its operation to within one Slack-side team, meaning shorter Matrix-side usernames for ghosts.

**Comment by leonerd** [comment]
Incoming channel (and user?) IDs may also be team-specific.

**Comment by leonerd** [comment]
On the subject of usernames, see also #24

**Comment by jaller94** [comment]
I'm closing this ticket that's almost 7 years old.
In my 2.5 years on this project, I haven't heard a discussion about single-team mode or other team-specific issues come up.
