### ISSUE TITLE
Puppets echo back across the bridge

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#234]

**Comment by Half-Shot** [comment]
@Cadair says this won't work for reactions.

**Comment by Cadair** [comment]
*(from memory back when I was implementing reactions)*

When sending a reaction to slack the API doesn't respond with an event ts. The API expects you to listen to the incoming events to get the event ID of the reaction based on the unique combination of `(parent_ts, sender, reaction_key)`.
