### ISSUE TITLE
Work out how regular users are supposed to deal with "channel IDs"

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-slack#26]
Currently to set up an linked room in the bridge, the configuration needs to know, among other things, the slack channel ID of the relevant slack channel. Unfortunately, as far as I can tell, users can't actually know this from the slack UI. It's not made apparent to them anywhere.

**Comment by leonerd** [comment]
Possible options:

 1. The bridge could look it up at configuration time, based on the current name of the channel (but since channels can be renamed in Slack it's best not to store that name in config). It can only do that if it has the team token for that team.

 2. We could forget using the channel ID and use the authentication token alone to identify the channel. I don't know the security implications of this. It's also very fragile because such tokens can be regenerated on Slack at any time.

 3. We could store a list of "pending associations", where the user has typed in a team + channel by name, and on receipt of a new message on a channel ID we don't yet know, look at the other fields and obtain the channel ID at that time. This *might* go horribly wrong if channels are renamed between users clicking the buttons and receiving a first message, but renames are rare so maybe that's OK.

**Comment by ara4n** [comment]
can you not call https://api.slack.com/methods/channels.list to get a current set of name->id mappings?

**Comment by leonerd** [comment]
@ara4n Yes, but only with appropriate permission. It's not publicly visible, so caling that requires a token; e.g. the team token.

**Comment by ara4n** [comment]
okay. then a variant of 3 perhaps? we look for a recognisable message from a known channel, and so infer which channel ID is which? (which is how we do it manually)

**Comment by leonerd** [comment]
Option 3 now implemented in 2334548 + b685668

**Comment by leonerd** [comment]
*headdesk*

It just occurred to me - we can use the Slack->Matrix webhook URL to encode extra information, in exactly the same way that the Matrix->Slack one does.

I.e. rather than using

    https://matrix.org/slackhook

we tell users to configure

    https://matrix.org/slackhook/SoMeRaNdOmToKeNhErE

then it will be possible to distinguish which is which. We just generate a new random token per Matrix room, so when messages arrive from Slack we know exactly which Matrix room to route the message into.

**Comment by leonerd** [comment]
I have this now mostly working on a branch; https://github.com/matrix-org/matrix-appservice-slack/commits/paul/route-by-webhook

Newly-provisioned rooms in this style work just fine, and the program runs alongside old ones. One important feature still lacking is an inplace "upgrade" of a (legacy) channel-ID-based link into an inbound ID one. I'll hack on that over the weekend and make a start upgrading our current links on Monday.

**Comment by leonerd** [comment]
This is now up and running live, and every room apart from the decentralizedweb room is now upgraded to this new format. I'll work that one out with them sometime.

**Comment by leonerd** [comment]
The last channel (decentralizedweb.#general) has now been updated to the new format. The old code has now been deleted. And there was much rejoicing...

(from me anyway)
