### ISSUE TITLE
Use user_change events to detect profile changes

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#275]
Rather than our hacky update upon each message. Since webhooks no longer have user tokens to fetch profile information from anyway, we can really save a lot of effort here.

**Comment by jaller94** [comment]
This is already implemented, if Team Sync is enabled. Otherwise, it is expected to not sync user changes.
I will add some documentation explaining the feature and how to configure it.

**Comment by Half-Shot** [comment]
I'll close this as the feature exists. The documentation for the feature can be considered an extension.
