### ISSUE TITLE
Mattermost -> Matrix only the first message is relayed

### ISSUE THREAD

**Issue by razcampagne** [matrix-org/matrix-appservice-slack#287]
Hi,

I am using the webhook api to bridge mattermost and matrix together.
While matrix -> mattermost works well, mattermost -> matrix only relays the first message.
From the second message on, I see in the logs SlackHookHandler receiving the webook POST, warning me there is no slack token (because I'm using webooks, I guess) but nothing more.

What could I be missing?

**Comment by Half-Shot** [comment]
Hey @razcampagne, could you configure your logs to be at the `debug` level and then PM me (@Half-Shot:half-shot.uk) the resulting log files from sending messages to Matrix from mattermost. Please include the full logs if you can, and I should be able to deduce what's gone on.
