### ISSUE TITLE
Work out how we can identify ourselves and not ignore other webooks

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-slack#29]
The gitter relaybot acts as a real bot user with a real user ID, so it can recognise reflections via gitter of its own messages, and ignore those on the inbound path.

By comparison, there is no slack user corresponding to our own specific webhook integration. All webhook integrations always appear under the special user ID of "USLACKBOT". This means that the logic to identify our own reflections also rejects every other message from any other webhook integration.

It's possible we can use the `bot_id` field.

**Comment by leonerd** [comment]
This might be possible to solve if we use `bot` OAuth2 scope instead of an incoming webhook. When we create that bot scope Slack tells us what the bot ID is.

**Comment by Half-Shot** [comment]
We do this now.

**Comment by tadzik** [comment]
We do?

It still looks hardcoded [here](https://github.com/matrix-org/matrix-appservice-slack/blob/develop/src/SlackHookHandler.ts#L273)
