### ISSUE TITLE
Linking in messages not present in Slack

### ISSUE THREAD

**Issue by joenas** [matrix-org/matrix-appservice-slack#292]
Message:
```json
{
  "type": "m.room.message",
  "sender": "@joenas:gottsnack.net",
  "content": {
    "body": "[link](https://jonnev.se)",
    "format": "org.matrix.custom.html",
    "msgtype": "m.text",
    "formatted_body": "<a href=\"https://jonnev.se\">link</a>"
  },
}
```
<img width="437" alt="Screenshot 2019-10-07 at 11 26 07" src="https://user-images.githubusercontent.com/1104793/66300522-c0282a00-e8f5-11e9-90e1-af1b3a50fa81.png">
<img width="453" alt="Screenshot 2019-10-07 at 11 29 04" src="https://user-images.githubusercontent.com/1104793/66300523-c0282a00-e8f5-11e9-962a-116a340b6f36.png">

**Comment by Half-Shot** [comment]
Will be fixed by #280

**Comment by joenas** [comment]
Including the `m.notice` thing @Half-Shot ?

**Comment by Half-Shot** [comment]
Nope, but that's a separate issue. We don't currently parse HTML from messages at all, so it won't be bridged. You should open a new issue for that though.

**Comment by auscompgeek** [comment]
Just tested with the matrix.org instance. I now only see the URL, the link text is discarded.

**Comment by Half-Shot** [comment]
Reference: https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22%3Chttp%3A%2F%2Fsomeurl%7Clike%20this%3E%22%7D

**Comment by joenas** [comment]
It works the other way around so I solved it that way for now! Sending formatted Slack links converts properly in Matrix 👌🏻

**Comment by jaller94** [comment]
Fixed by https://github.com/matrix-org/matrix-appservice-slack/pull/280
