### ISSUE TITLE
can't unlink, can't relink - slack integration basically broken now.

### ISSUE THREAD

**Issue by andreasnuesslein** [matrix-org/matrix-appservice-slack#308]
Okay so what happened is this:

we have a customer with whose Slack we want to integrate. They are admin there, so we gave them a user on our matrix and asked them to do that (given a little tutorial). It worked fine but then they threw out the riot_bridge on their side... I guess. We're a bit hazy on the details.

So we tried to repeat the process but the whole integrations modal seems a bit broken. Slack is not showing up as existing integration. When they click on it and then on `Event bridging` it does sometimes however still show `List Channels` and `Logout` neither of which does anything. Re-adding the integration on the `add to slack` button "works" as it doesn't throw any errors but then it's not really listed as existing and then lather rinse repeat.

So, they made me admin on their slack, I successfully hooked it all up. But then they disabled my account on their end and with it the integration also went away (obviously). After re-enabling my account I have the same problems as them now.  I tried a different matrix-room but it doesnt seem to help.

 The main room we tried this on is this: `!UzvVibSCSZfFegrWcn:matrix.dhrug.de` My user `@nuts:matrix.dhrug.de`, their user: `@neema:matrix.dhrug.de`.

Any help would be appreciated. (Don't know if I can conjure up the sammich and beer from over here though ;)

Cheers

**Comment by Half-Shot** [comment]
Hiya, so what I've gleamed from the database:

- !UzvVibSCSZfFegrWcn:matrix.dhrug.de is not bridged anywhere.
- @ nuts had an access token paired to it to get channel listings, but presumably this is broken because the app got removed.
- @ neema had nothing connected to them.

I've removed the access token from your account, so you should be able to go through the same flow. I will open a bug for this problem.

**Comment by andreasnuesslein** [comment]
Ahoy @Half-Shot ,

thank you for your help! Sadly it's still not working.

So it looked cleaner when I got to the "event bridging" screen - there was no more old "Your teams"-team. So I made sure everything was clean on the slack end as well - kicked out the riot_app there and relinked. It worked nicely up to the point where I again get this screen and the links don't do anything:

![image](https://user-images.githubusercontent.com/320080/67616257-f6f7ae80-f7d6-11e9-9a20-f6260974d53d.png)

Is it possible that this is somehow broken on Slacks side now, since you don't see any database entries?

Cheers

**Comment by Half-Shot** [comment]
Hiya, apparently I didn't see this message until now. This is a strange situation. We might need to coordinate this so I can see in the logs. I did manually run the query for channels in the slack api tester and got back 4 of yours, so there is nothing stopping this from working. Hit me up in a PM and we can debug this further.

**Comment by andreasnuesslein** [comment]
Ahoyhoy @Half-Shot ,

(sadly) I can't follow up on this anymore because they just joined our Matrix instance ( \o/ ) but also deactivated our accounts on their Slack now.

Thank you for your help nonetheless!

**Comment by Half-Shot** [comment]
That's probably a good outcome in the end then :laughing:

**Comment by mavigro** [comment]
Hi, I'm having a very similar problem, almost identical, and was wondering if I should open a new issue or resume this one.

**Comment by Half-Shot** [comment]
@manuroe can you create a new issue and share all the details you have?

**Comment by mavigro** [comment]
Hi, I think the last comment was meant for me. I''ll open a new a new issue. thx

**Comment by mavigro** [comment]
issue #321 created.
