### ISSUE TITLE
Public Attachments Matrix -> Slack get localhost link

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-appservice-slack#314]
I have a matrix room bridged to slack.
Matrix attachments have (to my awareness but at least in this case) public URLs.
This is handled correctly as described in doc:
>will receive the "public link" from protocols that have links to files without authentication

However the forwarded link is not correct because the domain is replaced by localhost:8008.

**Comment by auscompgeek** [comment]
Did you set homeserver.media_url in your config?

**Comment by HarHarLinks** [comment]
No. Why is it marked "optional"?
