### ISSUE TITLE
Matrix edits get duplicated on Slack

### ISSUE THREAD

**Issue by auscompgeek** [matrix-org/matrix-appservice-slack#316]
Whenever a message is edited on Matrix, the corresponding Slack message is edited correctly, but then a new message is sent to Slack with what looks like the fallback text (the new text prefixed with an asterisk).

(this is on the current matrix.org deployment; can provide event/room IDs to find logs if required)

**Comment by olmari** [comment]
This I can confirm. Whenever someone edits an message in matrix, it does get edited properly at slack, but also show fallback style mesage too. Seems to happend every time. Screenshot from slack side from matrix edit:
![Matrix to slack edit](https://user-images.githubusercontent.com/5422161/69008165-2326cb00-0950-11ea-8c5c-8fd3ce32eb44.png)
