### ISSUE TITLE
Images are bridged as filenames only from matrix to slack

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#319]
This looks likely like a formatting fail. It should be noted that files like PDFs are still being bridged across.

**Comment by olmari** [comment]
Wasn't this supposed to fix it? https://github.com/matrix-org/matrix-appservice-slack/commit/580241536dbfb22d74295185e7176c7542bc54c6 I'm just waiting to make this either make  into master and/or new release being made :)

**Comment by Half-Shot** [comment]
Yep, it just needs deploying I think

**Comment by Half-Shot** [comment]
Pretty sure we did this.
