### ISSUE TITLE
Default database fails

### ISSUE THREAD

**Issue by Sorunome** [matrix-org/matrix-appservice-slack#352]
turns out there is a `return` missing after this line https://github.com/matrix-org/matrix-appservice-slack/blob/master/src/datastore/NedbDatastore.ts#L165

**Comment by jaller94** [comment]
Permalink: https://github.com/matrix-org/matrix-appservice-slack/blob/09078b0b38a81cc6c0e5fa1f23c0b9bfa2944c50/src/datastore/NedbDatastore.ts#L165

The problem still exists.
