### ISSUE TITLE
Slack Snippets are silently ignored

### ISSUE THREAD

**Issue by davidar** [matrix-org/matrix-appservice-slack#37]
See https://get.slack.help/hc/en-us/articles/204145658-Create-a-snippet

**Comment by msmart** [comment]
Maybe this happens because message attachments are not part of the payload in the slack's Outgoing Webhook, see https://api.slack.com/outgoing-webhooks where it says:

> "Please note that the content of message attachments will not be included in the outgoing POST data."

**Comment by Half-Shot** [comment]
This has been fixed in develop
