### ISSUE TITLE
Fix the need for one integration per bridged channel

### ISSUE THREAD

**Issue by martinklepsch** [matrix-org/matrix-appservice-slack#39]
Bridging a larger Slack community onto Matrix would seemingly require one integration per channel. Since most communities are on a free plan there's a limit on the number of integrations that can be added and it's not very high (don't know the exact number but I'd guess it's below 10).

This makes bridging a larger number of rooms including user metadata not really possible.

**Comment by martinklepsch** [comment]
Hm, Yaniel in the Riot channel said this would be the case but it seems we were able to fully bridge two channels without an integration being added to the Slack account per channel.

**Comment by Cadair** [comment]
@Half-Shot This is closed by the EventsAPI stuff right?

**Comment by Half-Shot** [comment]
Ah yeah, I think it does :)
