### ISSUE TITLE
Managing integration not possible in non-public rooms

### ISSUE THREAD

**Issue by madduck** [matrix-org/matrix-appservice-slack#40]
While I can add the slackbot to a non-public (invite-only) room, if I later try to "Manage Integrations", I am told that no bridge exists (see screenshot).
![screenshot](https://cloud.githubusercontent.com/assets/195073/21014025/922928f6-bd5c-11e6-8fb0-a610a3890300.png)
Only after I change the room to public (which I can't really do in most cases), then can I manage the bridge.

**Comment by alexgleason** [comment]
After spamming this screen with the Slack incoming webhook, it did give me an outgoing one and the bridge worked. Unfortunately the outgoing hook didn't pass on Slack's end and the communication only goes one way, from Matrix to Slack. The room in Slack is also a private room.

The error on Slack says:

>our URL didn't respond with the value of the challenge parameter.

**Comment by jhave** [comment]
have same dilemma: do both ends of integration need to be public?

**Comment by erdnaxeli** [comment]
Maybe it will be fixed with the new event API support (#66).

**Comment by cinghiopinghio** [comment]
In this [link](https://api.slack.com/custom-integrations/outgoing-webhooks) the api documentations says:

> The outgoing webhook integration is only available in public channels.
> If you would like to get data out of private groups and DMs in real-time, try a slash command.

Using the Event API as in #66 it should be possible to access to private channels (depending on who authorize the matrix-slack bridge on the slack side). see [here](https://api.slack.com/events-api#permission_model).

**Comment by Half-Shot** [comment]
This should be possible with the new bot API
