### ISSUE TITLE
Linking room does not work if metric are disabled

### ISSUE THREAD

**Issue by erdnaxeli** [matrix-org/matrix-appservice-slack#406]
When I try to link a room, with `link` command and RTM mode, with metric disable, I got an error from [this line](https://github.com/matrix-org/matrix-appservice-slack/blob/develop/src/SlackClientFactory.ts#L237), because `ex.data.error` does not exist.

The real error comes from [here](https://github.com/matrix-org/matrix-appservice-slack/blob/develop/src/Main.ts#L801). Indeed this have no attribute `metricPuppets` when I look in debug. The attribute is never [initialized](https://github.com/matrix-org/matrix-appservice-slack/blob/develop/src/Main.ts#L208).

**Comment by Half-Shot** [comment]
I believe this got fixed.
