### ISSUE TITLE
Try RTM API instead of in+outbound webhooks

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-slack#41]
https://api.slack.com/rtm

In summary it seems:
  * We could use the RTM API to puppet for *individual users* who opt-in, in much the way that we're trying with the Gitter bridge.
  * Or, we could create an "app bot" account, that lets a bot user join Slack rooms. - https://api.slack.com/bot-users

**Comment by leonerd** [comment]
One tiny thorn appears to be that an "app bot" account is not able to set a room topic, so Matrix->Slack topic bridging wouldn't work in this case.

**Comment by erdnaxeli** [comment]
I agree we should use RTM API, it's much more powerfull than outgoing socket. But does an app bot can change it's avatar and username per message? I don't think so.

One idea is to use an app bot with RTM API only to get more information from message (mainly attachments)

**Comment by ara4n** [comment]
The way to do this would be to have the bridge act as a “puppeting” bridge - ie logging on with real slack credentials as a real user to mirror that user’s activity in Matrix. I think @Leonerd added this  to gitterbridge (but not yet deployed) but not slackbridge

**Comment by erdnaxeli** [comment]
Yes but I like the ability to bridge users who doesn't have a slack account.

And iirc there is already a puppet only slack bridge.

Le 2 oct. 2017 1:31 AM, "Matthew Hodgson" <notifications@github.com> a
écrit :

**Comment by Cadair** [comment]
@Half-Shot this can be closed by #89 right?

**Comment by Cadair** [comment]
or at least renamed to "support user puppeting"

**Comment by Half-Shot** [comment]
Closing this, and making #104 for puppeting.
