### ISSUE TITLE
PNG images are sent with `m.file` msgtype instead of `m.image`, causing failure to generate preview

### ISSUE THREAD

**Issue by williamkray** [matrix-org/matrix-appservice-slack#432]
PNG image files uploaded via normal matrix clients behave properly because their msgtype is `m.image`. Those that are created by Slack users are uploaded as type `m.file` and so matrix clients only prompt users to download the file, without showing any sort of preview of the image.

JPG image files use the appropriate msgtype and render correctly. GIF images do not, and behave similarly to png.

**Comment by williamkray** [comment]
the more i look at this, reviewing the source, the less it made sense... so i just tried using a very small png image, and the message/image upload was sent with the proper msgtype. so perhapse there's some sort of file processing issue because of the size or amount of time it takes.

**Comment by williamkray** [comment]
further testing makes this look sporadic, but somehow associated with filesize or processing time. here's an example of an incorrectly identified message upload:

```{
  "type": "m.room.message",
  "sender": "@slack_jobmachine_U03MCE1DE:jobmachine.org",
  "content": {
    "body": "external-content.duckduckgo.com.jpg",
    "info": {
      "mimetype": "",
      "size": 399412
    },
    "msgtype": "m.file",
    "url": "mxc://jobmachine.org/yVMqIZUrkqgBjxvAjWiisSbO"
  },
  "origin_server_ts": 1594932734623,
  "unsigned": {
    "age": 257
  },
  "event_id": "$va593EMssZzlMI6iMfbeU82W7WFPHBQKkAmm0wqhGMw",
  "room_id": "!nwbqPRuaJbSnQTzCmo:jobmachine.org"
}
```

**Comment by auscompgeek** [comment]
The `"mimetype": ""` seems rather suspicious here. Wonder when that'd be empty string.

**Comment by williamkray** [comment]
yeah i'm having a hard time finding consistency... it apparently can happen with all filetypes, but could be I/O related. if someone posts two pictures, one right after the other, i've seen the first one come through just fine, and the second one doesn't (missing mimetype and wrong msgtype) even if it's a significantly smaller filesize.

seems like either way, the process is running into some sort of race condition wherein it can't identify the mimetype of the file, and therefore just dumps an m.file message instead of the appropriate version.

my host (and therefore the media library for synapse) is on my server running an mdadm RAID6 array, so it's entirely possible that a slowdown in disk IO might be the root cause, but it seems like underperforming disk shouldn't cause a race condition like this. presumably if it the file.mimetype method doesn't return a result, it should hold off until the image has finished downloading/uploading/whateveritdoes and try again before returning a dumb response. i would say it could fall back to file extension as a backup but that presents a security vulnerability if a malicious file is added with a non-matching file extension that promotes execution in the app, etc.

**Comment by Half-Shot** [comment]
The mimetype seems to be coming from slack, so slack may be sending us empty mimetypes. This is quite rude of it.

**Comment by williamkray** [comment]
as a non-ts/js dev, the instructions are a little vague, my apologies if this isn't helpful:

i'm running the docker container, so i edited the .js file instead of the .ts file and restarted the container. 
the line i added was:

```log.warn(`BridgedRoom message.files returns: ${message.files}`)```

i got this as the result:

`BridgedRoom message.files returns: [object Object]`

hopefully that's what you're looking for? if you give me more explicit instructions, i'd be happy to rebuild the container from scratch or something and throw in all kinds of debug stuff in.

**Comment by Half-Shot** [comment]
@williamkray you were almost there, `log.warn(`BridgedRoom message.files returns`, message.files)` should work

**Comment by williamkray** [comment]
that definitely looks much more informative:

```
Jul-24 13:28:07.345 WARN BridgedRoom BridgedRoom message.files returns [
  {
    id: 'F017V99EM9A',
    created: 1595597282,
    timestamp: 1595597282,
    name: 'IMG_20200722_124144_012.jpg',
    title: 'IMG_20200722_124144_012.jpg',
    mimetype: '',
    filetype: '',
    pretty_type: '',
    user: 'U03MCE1DE',
    editable: false,
    size: 4042532,
    mode: 'hosted',
    is_external: false,
    external_type: '',
    is_public: false,
    public_url_shared: false,
    display_as_bot: false,
    username: '',
    url_private: 'https://files.slack.com/files-pri/T03MCE1DC-F017V99EM9A/img_20200722_124144_012.jpg',
    url_private_download: 'https://files.slack.com/files-pri/T03MCE1DC-F017V99EM9A/download/img_20200722_124144_012.jpg',
    permalink: 'https://jobmachine.slack.com/files/U03MCE1DE/F017V99EM9A/img_20200722_124144_012.jpg',
    permalink_public: 'https://slack-files.com/T03MCE1DC-F017V99EM9A-f8b6356777',
    is_starred: false,
    has_rich_preview: false
  }
]
```
i was able to post the same picture moments later, but this time i simply waited about 20 seconds between choosing the file for upload to slack, and hitting the "send" button... significantly different response which succeeded in sending the correct file preview/message type to matrix:

```
[
  {
    id: 'F017P486LFL',
    created: 1595597651,
    timestamp: 1595597651,
    name: 'IMG_20200722_124144_012.jpg',
    title: 'IMG_20200722_124144_012.jpg',
    mimetype: 'image/jpeg',
    filetype: 'jpg',
    pretty_type: 'JPEG',
    user: 'U03MCE1DE',
    editable: false,
    size: 3842948,
    mode: 'hosted',
    is_external: false,
    external_type: '',
    is_public: false,
    public_url_shared: false,
    display_as_bot: false,
    username: '',
    url_private: 'https://files.slack.com/files-pri/T03MCE1DC-F017P486LFL/img_20200722_124144_012.jpg',
    url_private_download: 'https://files.slack.com/files-pri/T03MCE1DC-F017P486LFL/download/img_20200722_124144_012.jpg',
    thumb_64: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_64.jpg',
    thumb_80: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_80.jpg',
    thumb_360: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_360.jpg',
    thumb_360_w: 270,
    thumb_360_h: 360,
    thumb_480: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_480.jpg',
    thumb_480_w: 360,
    thumb_480_h: 480,
    thumb_160: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_160.jpg',
    thumb_720: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_720.jpg',
    thumb_720_w: 540,
    thumb_720_h: 720,
    thumb_800: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_800.jpg',
    thumb_800_w: 800,
    thumb_800_h: 1067,
    thumb_960: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_960.jpg',
    thumb_960_w: 720,
    thumb_960_h: 960,
    thumb_1024: 'https://files.slack.com/files-tmb/T03MCE1DC-F017P486LFL-6e212eea8f/img_20200722_124144_012_1024.jpg',
    thumb_1024_w: 768,
    thumb_1024_h: 1024,
    original_w: 2976,
    original_h: 3968,
    thumb_tiny: 'AwAwACSKKVgAFKAenFTtcBWKlTwaogcGrEo+djnvQBN9oXuCPwoFwhPU1BvIA6UbWBBOOtIZOXyeM0m6mDpS4oAqdjV0KhyTnJNUMnn3rQC4J+tMQnkI3rTxar1yaEYA81MsynCAc0hjFh4pfKqyq4XmlwKAM54oYoix2u/qG71XZiAC3JPNXJGI+WTIzx061nytukOOlMEhck09WMcgIbt1FRc1aKxyx7VBLAUkDJVu5FzhN245zzS/bpP+eX86rqskY24P4GlzJ6NVaE6n/9k=',
    permalink: 'https://jobmachine.slack.com/files/U03MCE1DE/F017P486LFL/img_20200722_124144_012.jpg',
    permalink_public: 'https://slack-files.com/T03MCE1DC-F017P486LFL-a780271022',
    is_starred: false,
    has_rich_preview: false
  }
]
```

so the race condition is coming from Slack directly!

**Comment by Half-Shot** [comment]
Yeah, well that's one of the problems. This is slack sending us the message from it's real time API so we're not even calling an API, but we wouldn't expect the values to be empty. We *could* do a call to https://api.slack.com/methods/files.info if the metadata is empty and see what happens.

**Comment by Half-Shot** [comment]
Hopefully fixed in #450

**Comment by williamkray** [comment]
just updated my docker container to test this fix, and it seems to do the retry, but still is returning empty info. seems like it's still a race condition, as it depends on how quickly i send the slack message after choosing the file. unless i as the slack user wait for all "uploading..." messages to finish before sending the message to the channel, odds are high that it will fail to identify the mimetype on matrix. because i can't ask all users of the slack team to "please don't send image uploads until you've seen the slack dialogs complete", and because i'm not aware of whether mobile slack clients do this or not, this is still presenting an issue for me.

```
matrix-slack-bridge_1       | Aug-13 16:23:50.379 INFO SlackGhost Updating user information for U03MCE1DE
matrix-slack-bridge_1       | Aug-13 16:23:50.381 INFO BridgedRoom Slack file F019HAC3TDE is missing mimetype, fetching fresh info
matrix-slack-bridge_1       | Aug-13 16:23:51.590 INFO bridge [-] POST https://synapse.jobmachine.org/_matrix/media/r0/upload (@slack_jobmachine_U03MCE1DE:jobmachine.org) Body: {"type":"Buffer","data":[60,33,68,79,67,84,89,80,69,32,104,116,109,108,62,60,104
matrix-slack-bridge_1       | Aug-13 16:23:51.909 INFO bridge [-] POST https://synapse.jobmachine.org/_matrix/media/r0/upload (@slack_jobmachine_U03MCE1DE:jobmachine.org) HTTP 200 "{\"content_uri\":\"mxc://jobmachine.org/jGiWMXlpzkdbDDTzoiFgrXKi\"}"
matrix-slack-bridge_1       | sendEvent of type m.room.message in !owcQIQSSjVfxpxMmYB:jobmachine.org with txnId m1597335831912.3
matrix-slack-bridge_1       | Aug-13 16:23:51.913 INFO bridge [-] PUT https://synapse.jobmachine.org/_matrix/client/r0/rooms/!owcQIQSSjVfxpxMmYB%3Ajobmachine.org/send/m.room.message/m1597335831912.3 (@slack_jobmachine_U03MCE1DE:jobmachine.org) Body: "{\"body\":\"IMG_20200807_144413_HDR.jpg\",\"info\":{\"mimetype\":\"\",\"size\":
matrix-slack-bridge_1       | Aug-13 16:23:52.330 INFO bridge [-] PUT https://synapse.jobmachine.org/_matrix/client/r0/rooms/!owcQIQSSjVfxpxMmYB%3Ajobmachine.org/send/m.room.message/m1597335831912.3 (@slack_jobmachine_U03MCE1DE:jobmachine.org) HTTP 200 "{\"event_id\": \"$Xttgd67slTZDs3ZmHbl-op7Nw0zBNiXu98qC-zEtqeQ\"}"
matrix-slack-bridge_1       | Event sent to !owcQIQSSjVfxpxMmYB:jobmachine.org with event id $Xttgd67slTZDs3ZmHbl-op7Nw0zBNiXu98qC-zEtqeQ
matrix-slack-bridge_1       | Aug-13 16:23:52.464 INFO bridge ::ffff:172.31.0.5 - - [13/Aug/2020:16:23:52 +0000] "PUT /transactions/43936?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.18.0"
```

The above image not only failed to generate a thumbnail, but also failed to upload to matrix at all... when opening the file from matrix i just get an empty square (https://synapse.jobmachine.org/_matrix/media/r0/download/jobmachine.org/jGiWMXlpzkdbDDTzoiFgrXKi). i see this behavior regularly and i assume it's related to the inability to fetch the image properly from slack due to slack's processing tasks.

**Comment by Half-Shot** [comment]
Hmm, okay. The logs above seem to imply something got sent to matrix?

**Comment by williamkray** [comment]
yes, the message and an image _were_ sent to matrix, but the image appears to be corrupt and the message still shows no mimetype found.

for the log file posted above, here's what i sent in slack:
![Screenshot_20200813113010](https://user-images.githubusercontent.com/8409433/90172917-81a29d80-dd58-11ea-9135-846791fa7604.png)

here's what it looked like in matrix/element (disregard the deleted messages, those were previous tests):
![Screenshot_20200813112938](https://user-images.githubusercontent.com/8409433/90172968-93844080-dd58-11ea-90de-e18bb4732707.png)

here's the message source in element:
```{
  "type": "m.room.message",
  "sender": "@slack_jobmachine_U03MCE1DE:jobmachine.org",
  "content": {
    "body": "IMG_20200807_144413_HDR.jpg",
    "info": {
      "mimetype": "",
      "size": 5447457
    },
    "msgtype": "m.file",
    "url": "mxc://jobmachine.org/jGiWMXlpzkdbDDTzoiFgrXKi"
  },
  "origin_server_ts": 1597335832115,
  "unsigned": {
    "age": 224
  },
  "event_id": "$Xttgd67slTZDs3ZmHbl-op7Nw0zBNiXu98qC-zEtqeQ",
  "room_id": "!owcQIQSSjVfxpxMmYB:jobmachine.org"
}
```

and the link to the image in the previous comment is still live, you can see that the image file that was uploaded to matrix is corrupt and unreadable by any programs.

**Comment by Half-Shot** [comment]
Reading the file, it looks like a HTML file which looks like an authentication page. I'm going to guess that the token the bridge is using to authorize the download isn't accepted for some reason..

**Comment by Half-Shot** [comment]
Looks like this is also #465

**Comment by williamkray** [comment]
ah yes! wow, good spot. if i download the file and change it to an HTML ending and open it with firefox, it's definitely a slack authentication page for the slack team the bridge is connected to. i'll start following the other ticket as well.

**Comment by williamkray** [comment]
i've upgraded a few times in between submitting this ticket, and it seems like whatever was changed has resolved this in the stable branch docker container. i'm going to mark this as closed. thanks all!
