### ISSUE TITLE
How to deal with threads

### ISSUE THREAD

**Issue by hackel** [matrix-org/matrix-appservice-slack#45]
Today I kept seeing messages in Matrix that I wasn't seeing in the actual Slack web client.  I pulled out my hair for a while trying to figure out what was going on, thinking perhaps someone had blocked me personally or something, before eventually finding the messages in a thread from days earlier that I wasn't following.  I understand if Matrix doesn't support threaded conversations (yet, I hope!), but it would be extremely helpful if there was some kind of indicator that a message was a part of a threaded conversation, even something as simple as a ↳ before the message or something might be good enough.

**Comment by erdnaxeli** [comment]
Actually the webhook API the bridge is currently using is very basic. I just saw there should be a `thread_ts` field in the POST data, maybe it indicates the thread. This needs some testing.

**Comment by perissology** [comment]
with #66, this would only require a mapping between eventId & the msg ts. Then the msg corresponding to the `thread_ts` in the slack msg could be quoted or something in the matrix msg

**Comment by kiliankoe** [comment]
Some visual indication that a message is from a thread and not posted in the mainline channel would be fantastic. Otherwise I might be replying into the channel without knowing that nobody else is going to understand the context of that.

**Comment by Half-Shot** [comment]
Unsure if there is anything left to do from the bridge side. Matrix needs to support a more seperated thread use case, but this is outside the scope here.
