### ISSUE TITLE
OAuth2 configuration undocumented

### ISSUE THREAD

**Issue by almereyda** [matrix-org/matrix-appservice-slack#46]
The configuration schema contains entries for OAuth2. For those who know what it does, these should be self-explanatory. Yet the README.md does not contain info on how to use those.

See https://github.com/matrix-org/matrix-appservice-slack/blob/master/config/slack-config-schema.yaml#L24-L33 for reference.

**Comment by Half-Shot** [comment]
This is fixed in #202

**Comment by almereyda** [comment]
Thanks for the fix.
