### ISSUE TITLE
Users join then left on startup

### ISSUE THREAD

**Issue by erdnaxeli** [matrix-org/matrix-appservice-slack#464]
Hi,

I think the PR https://github.com/matrix-org/matrix-appservice-slack/pull/449 introduced a bug. With team_sync enabled for channels and users, I got the following behavior on startup:
1. all users in the slack team join the matrix room, even those who are not in the slack channel
2. then the users not in the slack channel leave the matrix room

This is pretty annoying. I looked a bit at the code and couldn't find what is wrong.

**Comment by erdnaxeli** [comment]
I think #463 is fixing it.

**Comment by Half-Shot** [comment]
Fixed in #463
