### ISSUE TITLE
Slack message referencing to a slack user is gibberish 

### ISSUE THREAD

**Issue by betz** [matrix-org/matrix-appservice-slack#49]
hey,

we have a slack bridge running, but when someone on slack references a user, it translates to something like '@U0TLNKQRL' instead of a username.
This has the side effect that person is not notified, nor no ones knows who is referenced.
We need to guess by the context. :)

If those reference id's stay the same, this seems fixable.

Cheers!
Tom

**Comment by Half-Shot** [comment]
I think I accidentally duped this in #81, but it's more recent anyhow. Sorry :z
