### ISSUE TITLE
500 Internal Server Error when adding Slack Bridge

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/matrix-appservice-slack#492]
**Describe the bug**
During the process to add the Slack bridge to a Matrix room, on the step where you select the Slack room. When clicking any room you get the error `Failed to make link: Bridge returned HTTP 500 Internal Server Error: Failed to join room`

**To Reproduce**
1. Create a unencrypted Matrix room on any server that can federate with the Matrix.org integration manager
1. Go to the integration manager, and select Slack bridge
1. Add bridge
1. Log in and select workspace or whatever Slack calls this
1. Click List Channels
1. Click any channel

**Expected behavior**
Not 500 Internal Server Error

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Desktop (please complete the following information):**
- All browsers and OS'

**Comment by ahangarha** [comment]
I am also facing the same issue. I am not sure if this would help but I cannot connect through webhook as well. I am guessing there is some issue from Slack side not matrix/element.

**Comment by trev-dev** [comment]
Able to replicate this issue as well. Can't seem to bridge to slack at all.

**Comment by Half-Shot** [comment]
The bug appears to be that:

```
Oct  1 10:31:41 lethe docker-slack-bridge[13465]: Oct-1 10:31:41.878 INFO bridge [-] POST http://http-priv.matrix.org/_matrix/client/r0/register (AS) Body: "{\"username\":\"slackbot\"}"
Oct  1 10:31:41 lethe docker-slack-bridge[13465]: Oct-1 10:31:41.932 ERROR bridge [-] POST http://http-priv.matrix.org/_matrix/client/r0/register (AS) HTTP 500 Error: "{\"errcode\":\"M_UNKNOWN\",\"error\":\"Internal server error\"}"
Oct  1 10:31:41 lethe docker-slack-bridge[13465]: Oct-1 10:31:41.933 ERROR Main Failed to handle $AsSfzanfywlZZEfb8Q2dj0_CEQvUkKPC8_fRBG9GKHI (!blah:half-shot.uk) Error: Failed to join room
Oct  1 10:31:41 lethe docker-slack-bridge[13465]:     at Intent._ensureJoined (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/intent.js:669:56)
Oct  1 10:31:41 lethe docker-slack-bridge[13465]:     at runMicrotasks (<anonymous>)
Oct  1 10:31:41 lethe docker-slack-bridge[13465]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Oct  1 10:31:41 lethe docker-slack-bridge[13465]:     at async Main.onMatrixEvent (/usr/src/app/lib/Main.js:404:17)
```

which should be fixed in the latest release.

**Comment by kevincox** [comment]
I'm seeing this on the element.io/matrix.org setup.
