### ISSUE TITLE
Bridged media are sent as two matrix messages, which makes them unreplyable.

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#498]
Because we bridge media as two messages, it means the bridge cannot determine which one should be replied to. We insert both messages into the database with the same `slackts`. Somehow, we need to keep the information that both events exist without impacting the threading.

A suggestion might be to have the image use a separate column for it's slackts, and just ensure we delete that row when we redact the image.

**Comment by jaller94** [comment]
Duplicate or closely related to https://github.com/matrix-org/matrix-appservice-slack/issues/486
