### ISSUE TITLE
Onboarding users with puppeting

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#501]
Currently puppeting oneself requires knowing to message the bot user, and logging in. This however is not very user friendly. The ideal process would be:

- The bridge keeps a track of matrix users in it's rooms.
- If a user is in a room, or joins it and is neither puppeted nor has a DM with the bot already: it creates a DM
- The bot should then give a friendly (word-smithed) introduction to the bridge and explain that they need to authenticate
   to get the best experience.
- A link should be provided which will take them to a web page that gives them the option of signing into their Slack account, or signing up to the workspace if they haven't already.
- The oauth process continues as normal, and the user should get one final message once the process is complete.

**Comment by Cadair** [comment]
> that they need to authenticate to get the best experience.

that they can authenticate if they want to be able to receive DMs / private channels from slack.
