### ISSUE TITLE
Do not join Slack members to a room if they are puppeted

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#511]
If the matrix user isn't in the room, invite them.

**Comment by Half-Shot** [comment]
I couldn't reproduce this bug at all.

**Comment by erdnaxeli** [comment]
Is this the bug you were thinking of? This user is puppeted on slack side.

![2020-09-28-141312_467x183_scrot](https://user-images.githubusercontent.com/479441/94430828-c792b400-0194-11eb-9b89-5e3bf5fda3c9.png)

**Comment by Half-Shot** [comment]
That's okay because you sent a message from the other side?

**Comment by erdnaxeli** [comment]
Yep that's what I did.
