### ISSUE TITLE
Pills do not highlight Slack users

### ISSUE THREAD

**Issue by eternaleye** [matrix-org/matrix-appservice-slack#52]
It's understandable that simply typing a user's display name isn't converted to a Slack-side highlight, as that would likely result in false positives. However, the recent "Pill" behavior introduced in Riot offers a clear signal that a user was intentionally denoted. It would be nice to support this.

Currently, in order to ping a Slack user, one has to use an @ prefix to their name - and this does not work together with tab completion.

**Comment by erdnaxeli** [comment]
It should be fixed.
