### ISSUE TITLE
Slack message can fail to bridge if transforming a channel mention fails

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#524]
The bridge will try to fetch `m.room.canonical_alias` state for the room mentioned (in order to get the right alias), and if it fails to get the event then the code will throw and subsequently fail to bridge the message. This is obviously not ideal, and we should fall back to textual representation.

**Comment by Cadair** [comment]
Should also be fixed by #517

**Comment by Half-Shot** [comment]
I've fixed this one now because it's impacting enough folks.
