### ISSUE TITLE
Provide a way to promote another user to admin in a automatically provisioned room

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-appservice-slack#532]
So that you can later kick the bridge out and retain control of the room

**Comment by psrpinto** [comment]
Related to/duplicate of https://github.com/matrix-org/matrix-appservice-slack/issues/496

**Comment by jaller94** [comment]
Closing as duplicate of https://github.com/matrix-org/matrix-appservice-slack/issues/496
