### ISSUE TITLE
Main Ignoring ev for matrix room with unknown slack channel in admin room

### ISSUE THREAD

**Issue by kennedyshead** [matrix-org/matrix-appservice-slack#542]
**Describe the bug**
I cant get the bridge to take any commands in the admin room

```
Nov 11 22:08:09 [499037]: Nov-11 22:08:09.074 INFO bridge 127.0.0.1 - - [11/Nov/2020:21:08:09 +0000] "PUT /transactions/17?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.11.0"
Nov 11 22:08:09 [499037]: Nov-11 22:08:09.081 WARN Main Ignoring ev for matrix room with unknown slack channel: !roomid:room.url
Nov 11 22:08:09 knutas-backend matrix-stack[499037]: Nov-11 22:08:09.081 INFO Main Handled $blablabla (!roomid:room.url)
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Half-Shot** [comment]
Are you still experiencing this problem? Did you specify the admin room in the config?

**Comment by christianbader** [comment]
Same problem here. I specified the admin room in the config but still receiving:
```
Feb 02 17:23:03 matrix matrix-appservice-slack[64496]: Feb-2 16:23:03.127 INFO bridge ::ffff:172.18.0.4 - - [02/Feb/2021:16:23:03 +0000] "PUT /transactions/103?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.26.0"
Feb 02 17:23:03 matrix matrix-appservice-slack[64496]: Feb-2 16:23:03.146 WARN Main Ignoring ev for matrix room with unknown slack channel: !JZRUQCeZnYQQwtkBIG:xxx.xyz
Feb 02 17:23:03 matrix matrix-appservice-slack[64496]: Feb-2 16:23:03.147 INFO Main Handled $1Buoi-aiHycoevL_kZ4RWIdxCX-loIMvgaCl6jKkQaU (!JZRUQCeZnYQQwtkBIG:xxx.xyz)
```
For me it seems that the link command issued in the admin channel has no effect.
Any thoughts?

**Comment by richardbeumer** [comment]
Same issue here:
```

Jun-11 20:56:03.471 WARN Main Ignoring ev for matrix room with unknown slack channel: !ksRGnrCkKsyEQYdNco:xxx.zzz
Jun-11 20:56:03.471 INFO Main Handled $0pECGq-za4mHx4rZEmHOSOHPE1rkh7lWawzRSk4XYTQ (!ksRGnrCkKsyEQYdNco:xxx.zzz)
```

I'm also thinking the link command does nothing

**Comment by vrutkovs** [comment]
I've hit the similar issue when I first invited slack bot in the channel and then updated `matrix_admin_room`. Kicking the bot and re-inviting it again helped

**Comment by trololo9000** [comment]
Same here, bridge doesn't want  :-(
Sep-14 17:10:26.228 WARN Main Ignoring ev for matrix room with unknown slack channel: [my admin room id]
Sep-14 17:10:26.228 INFO Main Handled $[long random id string] ([my admin room id])

**Comment by trololo9000** [comment]
Solved! I created another unencrypted control room, put the new room id into the matrix_admin_room setting in the config.yaml, restarted everything, works.

**Comment by sneakers-the-rat** [comment]
Definitely need to add that the admin room seems to need to be unencrypted for it to work with the default/documented config
