### ISSUE TITLE
Ignoring message with bad slackhook URL / 

### ISSUE THREAD

**Issue by dajohi** [matrix-org/matrix-appservice-slack#61]
Why is it bad?

what does url.match expect the url to look like?
can you give an example?

**Comment by dajohi** [comment]
I think the README is missing a final step.  It requires switching the webhook url to /inbound_id  where inbound_id is a 32 char id.

**Comment by erdnaxeli** [comment]
I don't understand your problem.

**Comment by p-thurner** [comment]
@erdnaxeli , I think @dajohi refers to the part in the README.md about "Provisioning", step 4, outgoing webhooks.
It states "Add a URL to this web hook pointing back at the application service port you configured during setup.", so I understood this to be http://matrix.example.com:9898.
When I use this, I get:

```
Received slack webhook POST /: {"token":"bar","team_id":"T90UV79CP","team_domain":"foobar","service_id":"12345","channel_id":"123456789","channel_name":"blunix","timestamp":"1517174338.000012","user_id":"*D38LD83C","user_name":"someone_slack","text":"test"}
Ignoring message with bad slackhook URL /
```

What is the correct URL to post to? How does one determine the correct inbound_id?

**Comment by tlaporte** [comment]
Did anyone figure this out? I am quite confused by this.

**Comment by p-thurner** [comment]
I couldn't figure it out so far :( ping @erdnaxeli 
Or maybe @dajohi figured it out by now?

**Comment by tlaporte** [comment]
Oh, I see. Once you make the link successfully, the bot tells you what your inbound url should be. The identifier is included.

**Comment by tlaporte** [comment]
So, if you issue a link command with just the room and webhook link (the incoming slack one), it will create a linked room entry that is incomplete. 

If you take the URL it gives you (add a slash if you need to after your domain name), and put that in your outgoing slack hook, all you have to do to complete the link is send a message in the linked slack channel (just like the documentation says you should do to get the slack channel id). 

You need to add the slackbot to the matrix channel you are linking as well.

**Comment by RameshThota87** [comment]
@tlaporte , Can you please elaborate more. I am also facing the same issue. If possible can share the steps or screenshots to link command. I installed slack bridge and  synapse in two different machines.

**Comment by Half-Shot** [comment]
Closing because I don't believe there is any work to be done on this issue.
