### ISSUE TITLE
Matrix Bridge - 500 Internal Server Error

### ISSUE THREAD

**Issue by sitiom** [matrix-org/matrix-appservice-slack#617]
**Describe the bug**
When trying to authorize the Element Bridge app to slack, I get an HTTP 500 error.

**To Reproduce**
1. Create an unencrypted Matrix room on any server that can federate with the matrix.org integration manager
2. Go to the integration manager, and select Slack bridge -> Add bridge
2. Select your workspace and allow
3. See blank screen

**Expected behavior**
Not 500 Internal Server Error

**Screenshots**
![Blank Screen](https://user-images.githubusercontent.com/56180050/134493852-f70b2536-6874-47bd-be74-e55eb0b1db2e.png)

**Desktop (please complete the following information):**
 - All browsers and OS

**Comment by Half-Shot** [comment]
`testbridge.slack.com` isn't our domain?

**Comment by sitiom** [comment]
> `testbridge.slack.com` isn't our domain?

`testbridge` is the workspace I have created in slack to test the bridge.

**Comment by Half-Shot** [comment]
Hiya, having investigated this it looks like an issue in Slack that's affecting the Element bridge. We're continuing to delve into it and will update when we have more.

**Comment by Half-Shot** [comment]
Hey folks, we believe this is now fixed. Slack rolled out an update to strictly validate redirect uris (so the URIs provided by the bridge had to exactly match the URIs provided in the Slack app settings). We had a slight error there which we fixed, and it now appears to work A-OK.

Let me know if anyone believes it's still broken.
