### ISSUE TITLE
Support threads with m.thread relation (MSC3440)

### ISSUE THREAD

**Issue by jaller94** [matrix-org/matrix-appservice-slack#634]
Threads are being added to the Matrix protocol soon. Because Slack already supports threads in its protocol and interface, it would be good to bridge that correctly. Currently, Slack threads are bridged as replies.

Related issues:
* Meta issue: https://github.com/vector-im/element-meta/issues/3
* MSC3440: https://github.com/matrix-org/matrix-doc/pull/3440

## Definition of Done
* [x] Slack threads are bridged to Matrix as `m.thread` relations – removing the reply relation we currently set.
* [x] Matrix threads are bridged to Slack as threads.

**Comment by abmantis** [comment]
What would be the behavior in clients that do not implement threads yet? Will they still fallback to replies?

**Comment by jaller94** [comment]
No, the fallback will like be that the messages are shown without context in the main thread.
This is unlikely to affect the plan of implementing this in a bridge once it's in the stable Matrix Spec.

**Comment by abmantis** [comment]
Will this be only implemented when this gets into the stable spec? :(

**Comment by Half-Shot** [comment]
We're planning to implement this sooner.
