### ISSUE TITLE
Slack → Matrix message delivery stopped working

### ISSUE THREAD

**Issue by nukeador** [matrix-org/matrix-appservice-slack#647]
Since Wednesday, the messages from Slack to Matrix direction stopped being delivered. New users and usernames changes are going through. 

Messages from Matrix to Slack are showing up.

Using the official Slack bridge integration from matrix.org homeserver.

Cheers.

**Comment by cryptix** [comment]
Same issue. Would like to help get more insights here but I feel like it's pretty much impossible to get introspection without hosting this service myself...

**Comment by susebus** [comment]
can confirm this issue

**Comment by cryptix** [comment]
@Half-Shot posted yesterday that a fix will be deployed. I'm now getting messages from slack in my test setup. 🎉

**Comment by Half-Shot** [comment]
Apologies folks, it was a dud update. Fix was in #648
