### ISSUE TITLE
Usernames going away?

### ISSUE THREAD

**Issue by andrewshadura** [matrix-org/matrix-appservice-slack#65]
See https://api.slack.com/changelog/2017-09-the-one-about-usernames
It seems it has already started:
![kmpjipqdudfbwxqtyebeyqij](https://user-images.githubusercontent.com/309253/34730683-6bd5cb0e-f560-11e7-9b47-7ae050997087.png)

**Comment by andrewshadura** [comment]
What exactly is okay? All Matrix users now look the same, they're unidentifiable.

**Comment by erdnaxeli** [comment]
Well, if I understand correctly the changelog, I think the bridge should still work. And I have no problem with username :s.

**Comment by andrewshadura** [comment]
Well, in practice it doesn't, all messages come through with identical avatars and the same nickname, which is incoming-webhook. And it matches the behaviour the blog post described (saying that username should not be included in the messages and will be ignored at some point in future).

**Comment by erdnaxeli** [comment]
The blog post does not say that:

> **Slack apps and their bot users** should not use the username field when authoring a message. The username is part of your app's configuration and will not always be settable at runtime.

And on the incoming webhook documentation:

> You cannot override the default username, icon, or channel for incoming webhooks attached to **Slack apps**. Instead, these values will stubbornly inherit from the associated Slack app configuration.

The bridge is not an app (so far), so it should be ok. Maybe I am missing something.

**Comment by andrewshadura** [comment]
In my understanding, anything that uses a webhook in fact is an app.

In any case, the bridge doesn't work properly, and I've no idea whether that can be fixed or not.

**Comment by andrewshadura** [comment]
Indeed, *Incoming Webhooks* **is** an app.

**Comment by andrewshadura** [comment]
Right, it's not yet *that* bad.
When I manually ran this:

    curl -X POST -H 'Content-type: application/json' --data '{"text":"Jeeeej", "icon_url": "https://avatars2.githubusercontent.com/u/309253", "username": "andrewsh", }'   https://hooks.slack.com/services/SIKRITSIKRIT/ANOTHERSECRET

It works:
![2018-01-16_13-15-26](https://user-images.githubusercontent.com/309253/34988545-5a941fbc-fabf-11e7-97e6-706783f38fe4.png)

When posting on Matrix, I only see this:
![2018-01-16_13-15-57](https://user-images.githubusercontent.com/309253/34988583-7f3cb32e-fabf-11e7-8f24-920f6e13470b.png)

**Comment by andrewshadura** [comment]
It seems to be working once again:
![image](https://user-images.githubusercontent.com/309253/37243136-19c568a8-2475-11e8-8bc4-656632df83f0.png)
