### ISSUE TITLE
Messages from Slack are not synced to Matrix room

### ISSUE THREAD

**Issue by tibeer** [matrix-org/matrix-appservice-slack#651]
**Describe the bug**
Messages from Slack are not synced to Matrix room.

**To Reproduce**
1. Send message from Element Matrix client
2. Message get's synced to Slack room
3. Send a message from Slack client
4. Message doesn't get synced to Matrix room

**Expected behavior**
Messages from Slack room get synced to Matrix room

**Screenshots**
![Bildschirmfoto 2022-01-03 um 10 42 42](https://user-images.githubusercontent.com/39375770/147916946-058f81a9-f610-4c00-a844-0de100c59c4d.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Element: 1.9.8

**Comment by tadzik** [comment]
Hey @tibeer,

Can you verify that the Slack bot is present on the Slack channel you're bridging?

**Comment by tibeer** [comment]
@tadzik jep, already checked that. The bot is present.

**Comment by tadzik** [comment]
On the screenshot I can only see the Matrix bot being in the Matrix room – not the Slack bot being there on the Slack side of things – the bridge needs both to function.

**Comment by tibeer** [comment]
On the Slack-Screenshot in the message at 10:34 is written that Element Bridge joined also the chat. I used the command displayed from Matrix side: `/invite @element_bridge` so I assume it's there.

**Comment by tadzik** [comment]
I see. The `/invite` looks good, though the result is quite confusing. For me it ends up being something like this:

![image](https://user-images.githubusercontent.com/86378/148064991-04e1596a-c5da-4471-99a9-09bf3f555a89.png)

I can then also see the Element Bridge on the channel's integration list:

![image](https://user-images.githubusercontent.com/86378/148065126-e9c1c9d6-402a-48ef-8df3-290e82a4335b.png)

It seems like, somehow, a wrong user/bot was added to the channel, making the Slack->Matrix messages not pass through.

Can you verify if the Integration is added to the channel as expected, and if not, perhaps try inviting `@element_bridge` again and checking if the right one gets added this time?

For the record, the issue of the bot not being in the bridged channel is common enough (while being hard enough to spot) that we now have an issue tracking it as a UX bug: https://github.com/matrix-org/matrix-appservice-slack/issues/653

**Comment by tibeer** [comment]
@tadzik awesome! I saw the App integration in the channel. After I kicked out the app from the slack chat room and even from the slack organization and than re-added the app to the slack org followed by adding it to the slack room again, it works now! Issue solved for me.

**Comment by tadzik** [comment]
Glad to hear that :) Thanks for your report.
