### ISSUE TITLE
2 unlink commands before 1st is done, bot goes invalid state

### ISSUE THREAD

**Issue by olmari** [matrix-org/matrix-appservice-slack#660]
**Describe the bug**
On version https://github.com/matrix-org/matrix-appservice-slack/commit/9705cc00c9bf6b75409bdd4e93c1166226bf4d2c aka current master, same with tag 1.10.0.

In slack bridge/bot matrix management room, issue 2 (or more) unlink commands in rapid way (script), bot starts to give invalid answer to 2nd unlink command and for _anything_ written in room later on. Only bridge restart helps then.

Undetermined is it all admin commands or just unlink.

Example:

```
leave !<id1>:hacklab.fi
leave !<id2>:hacklab.fi

Draining 0 ghosts from !<id1>:hacklab.fi
Drained
Missing required argument: room

help

Missing required argument: room

asdf

Missing required argument: room
```

**To Reproduce**
1. Go to slack integration management room
2. Give 2 (or more) unlink commands in rapid succession so that 2nd command is given before 1st one has answered back
3. See bridge answering successfully to 1st query and error out to 2nd...
4. ...and giving same error to any command thereon in room, valid command or not.

**Expected behavior**
Execute each command in admin room when possible and process the real request.

**server:**
 - OS: Debian Bullseye
 - Appservice-slack https://github.com/matrix-org/matrix-appservice-slack/commit/9705cc00c9bf6b75409bdd4e93c1166226bf4d2c and 1.10.0

**Comment by carpenike** [comment]
Also have the same error, although this is with subsequent link commands. Only way to "fix" it is to restart the bridge.

**Comment by AndrewFerr** [comment]
Whoops -- didn't mean to push straight to `develop` without a review first.

**Comment by AndrewFerr** [comment]
Merged for real this time! https://github.com/matrix-org/matrix-appservice-slack/pull/717
