### ISSUE TITLE
Docker build complains about EBADENGINE

### ISSUE THREAD

**Issue by tadzik** [matrix-org/matrix-appservice-slack#681]
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'matrix-appservice-slack@1.11.0',
npm WARN EBADENGINE   required: { node: '>=12 16<=' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
```

Node >16 is fine to use, it's just needlessly excluded in package.json version ranges. We even build the docker images from `node:16-bullseye-slim`

**Comment by Half-Shot** [comment]
I suspect the idea at the time was to avoid allowing newer version we've not tested, but tbh `engine` is too strict.
