### ISSUE TITLE
Slack -> Matrix bridging not working

### ISSUE THREAD

**Issue by Radvendii** [matrix-org/matrix-appservice-slack#757]
I followed the getting started and linking channels guides, and managed to get matrix -> slack bridging working, but nothing happens when i send a message in the slack channel. There aren't even any logs generated in the `matrix-appservice-slack` service. I found #651, and tried removing and re-adding the app, but that didn't help.

**Comment by Radvendii** [comment]
Wait I do see some error messages earlier on in startup
```
{"module":"MatrixHttpClient","data":["(REQ-1) GET http://[::1]:8008/_matrix/client/v3/account/whoami"],"level":"debug"}
{"module":"MatrixHttpClient","data":["(REQ-2) POST http://[::1]:8008/_matrix/client/v3/join/REDACTED"],"level":"debug"}
{"module":"MatrixHttpClient","data":["(REQ-2) { errcode: 'M_UNKNOWN', error: 'No known servers' }"],"level":"error"}
{"module":"Main","data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error"}
{"module":"MatrixHttpClient","data":["(REQ-3) GET http://[::1]:8008/_matrix/client/v3/joined_rooms"],"level":"debug"}
{"module":"Main","data":["Ensuring the bridge bot is registered"],"level":"info"}
{"module":"Intent","data":["Checking if user @slackbot:proqqul.net is registered"],"level":"debug"}
{"module":"MatrixHttpClient","data":["(REQ-4) POST http://[::1]:8008/_matrix/client/v3/register"],"level":"debug"}
{"module":"MatrixHttpClient","data":["(REQ-4) { errcode: 'M_USER_IN_USE', error: 'User ID already taken.' }"],"level":"debug"} 

```

**Comment by Radvendii** [comment]
Tried setting `$MATRIX_PORT` to 5858 as per #730, but that doesn't help.

**Comment by Radvendii** [comment]
never mind, this **did** solve the problem, even though the error messages didn't go away.

**Comment by kneescars** [comment]
@Radvendii hello. Could you let me know how you solved it? I am getting that same exact message.

**Comment by Radvendii** [comment]
I don't remember. But according to what I said here, I set `$MATRIX_PORT` to 5858. Either as an environment variable or in slack-registration.yaml
