### ISSUE TITLE
Error: Cannot find module 'slackdown'

### ISSUE THREAD

**Issue by g-goessel** [matrix-org/matrix-appservice-slack#88]
Hi
I have this issue when I try to build the app.
The solution is  to change `var slackdown = require('slackdown');` to `var slackdown = require('Slackdown');`

I didn't even know that node modules were case sensitive...

**Comment by Half-Shot** [comment]
O.o first for me... Wonder how that got broke

**Comment by g-goessel** [comment]
Oh wait it is not fixed yet
it works if I `npm install slackdown` but if it uses your repo it still fails
will investigate

**Comment by Half-Shot** [comment]
Much appreciated. My repo was a tiny change, but I had to do a build because their system is weird.
